(()=>{const $=id=>document.getElementById(id);const cfg=window.FIREBASE_CONFIG;let db,peer,conn,roomId,isHost=false,localURL,localStream;const video=$("video");function status(x){$("status").textContent=x}function rid(){return Math.random().toString(36).slice(2,9).toUpperCase()}function roomURL(id){return location.origin+location.pathname+"?room="+id}function send(x){if(conn?.open)conn.send(x)}function init(){if(!firebase.apps.length)firebase.initializeApp(cfg);db=firebase.database()}function addMsg(n,t){let d=document.createElement("div");d.className="msg";d.textContent=n+": "+t;$("messages").appendChild(d)}function capture(){if(!video.captureStream){alert("Chrome/Edge latest version එක use කරන්න.");return false}localStream=video.captureStream();return localStream.getVideoTracks().length>0}

$("videoInput").onchange=e=>{let f=e.target.files[0];if(!f)return;if(localURL)URL.revokeObjectURL(localURL);localURL=URL.createObjectURL(f);video.src=localURL;video.load();$("fileName").textContent=f.name;status("Video ready")};

$("createBtn").onclick=()=>{if(!$("videoInput").files[0])return alert("Video select කරන්න");init();roomId=rid();isHost=true;$("roomLink").value=roomURL(roomId);$("copyBtn").disabled=false;$("role").textContent="HOST";if(!capture())return;peer=new Peer("wt-"+roomId,{debug:1});peer.on("open",id=>{db.ref("rooms/"+roomId).set({hostPeer:id,playing:false,time:0,users:1});status("Room created 🟢")});peer.on("connection",c=>{conn=c;wire(c)});peer.on("call",call=>{if(!localStream)capture();if(localStream){call.answer(localStream);status("Video stream sent 🟢")}});peer.on("error",e=>status("Peer: "+e.type))};

$("joinBtn").onclick=async()=>{init();let id=new URLSearchParams(location.search).get("room")||$("roomLink").value.split("room=")[1];if(!id)return alert("Room link open කරන්න");roomId=decodeURIComponent(id);isHost=false;$("role").textContent="GUEST";peer=new Peer({debug:1});peer.on("open",async()=>{let s=await db.ref("rooms/"+roomId).get();if(!s.exists())return alert("Room not found");conn=peer.connect(s.val().hostPeer,{reliable:true});wire(conn);let call=peer.call(s.val().hostPeer,new MediaStream());call.on("stream",stream=>{video.srcObject=stream;video.controls=false;video.play().then(()=>status("Live video 🟢")).catch(()=>status("Video connected — Play click කරන්න"))});call.on("error",e=>status("Video call error"))})};

function wire(c){c.on("open",()=>{status("Connected 🟢");if(isHost)c.send({type:"state",playing:!video.paused,time:video.currentTime});else c.send({type:"request-state"})});c.on("data",m=>{if(m.type==="state"&&!isHost){let t=Number(m.time)||0;if(Math.abs(video.currentTime-t)>.35)video.currentTime=t;m.playing?video.play().catch(()=>{}):video.pause()}if(m.type==="request-state"&&isHost)send({type:"state",playing:!video.paused,time:video.currentTime});if(m.type==="chat")addMsg(m.name,m.text)})}

function sync(){if(isHost){let x={type:"state",playing:!video.paused,time:video.currentTime};send(x);if(db&&roomId)db.ref("rooms/"+roomId).update({playing:x.playing,time:x.time})}}video.onplay=sync;video.onpause=sync;video.onseeked=sync;

$("copyBtn").onclick=async()=>{await navigator.clipboard.writeText($("roomLink").value);status("Link copied ✓")};$("sendBtn").onclick=()=>{let t=$("chatInput").value.trim();if(!t)return;addMsg("You",t);send({type:"chat",name:"User",text:t});$("chatInput").value=""};$("chatInput").onkeydown=e=>{if(e.key==="Enter")$("sendBtn").click()};window.onload=()=>{init();let id=new URLSearchParams(location.search).get("room");if(id)$("roomLink").value=roomURL(id)}})();