(()=>{"use strict";
const $=id=>document.getElementById(id),video=$("video");let db=null,peer=null,conn=null,mediaCall=null,roomId=null,isHost=false,localURL=null,localStream=null;
function log(t,type="ok"){let d=document.createElement("div");d.className="line "+type;d.textContent=(type==="ok"?"✓ ":type==="bad"?"✗ ":type==="warn"?"⚠ ":"• ")+t;$("debug").appendChild(d);$("debug").scrollTop=$("debug").scrollHeight;console.log(t)}
function status(t){$("status").textContent=t}
function rid(){return Math.random().toString(36).slice(2,9).toUpperCase()}
function roomURL(id){return location.origin+location.pathname+"?room="+encodeURIComponent(id)}
function send(x){if(conn?.open){conn.send(x);return true}return false}
function chat(n,t){let d=document.createElement("div");d.className="msg";d.textContent=n+": "+t;$("messages").appendChild(d)}
function initFirebase(){try{if(!firebase.apps.length)firebase.initializeApp(window.FIREBASE_CONFIG);db=firebase.database();log("Firebase initialized");return true}catch(e){log("Firebase error: "+e.message,"bad");return false}}
function capture(){try{if(!HTMLVideoElement.prototype.captureStream){log("captureStream unavailable","bad");return false}localStream=video.captureStream(30);log("Host MediaStream created");log("Video tracks: "+localStream.getVideoTracks().length,localStream.getVideoTracks().length?"ok":"bad");log("Audio tracks: "+localStream.getAudioTracks().length,localStream.getAudioTracks().length?"ok":"warn");return localStream.getVideoTracks().length>0}catch(e){log("captureStream failed: "+e.message,"bad");return false}}
function mediaInfo(){const v=video.videoWidth+"x"+video.videoHeight;log("Video element: "+v);log("readyState: "+video.readyState);log("networkState: "+video.networkState)}
window.addEventListener("error",e=>log("JS error: "+e.message,"bad"));window.addEventListener("unhandledrejection",e=>log("Promise error: "+(e.reason?.message||e.reason),"bad"));
log("HTML / JavaScript loaded");log("HTTPS: "+(location.protocol==="https:"||location.hostname==="localhost"?"YES":"NO"),location.protocol==="https:"||location.hostname==="localhost"?"ok":"warn");log("WebRTC: "+(window.RTCPeerConnection?"YES":"NO"),window.RTCPeerConnection?"ok":"bad");log("captureStream: "+(HTMLVideoElement.prototype.captureStream?"YES":"NO"),HTMLVideoElement.prototype.captureStream?"ok":"bad");log("Firebase SDK: "+(window.firebase?"LOADED":"MISSING"),window.firebase?"ok":"bad");log("PeerJS SDK: "+(window.Peer?"LOADED":"MISSING"),window.Peer?"ok":"bad");log("config.js: "+(window.FIREBASE_CONFIG?"LOADED":"MISSING"),window.FIREBASE_CONFIG?"ok":"bad");

$("videoInput").onchange=e=>{const f=e.target.files[0];if(!f)return;if(localURL)URL.revokeObjectURL(localURL);localURL=URL.createObjectURL(f);video.srcObject=null;video.src=localURL;video.load();$("fileName").textContent=f.name;$("videoHint").textContent="Local video ready";status("Video ready");log("Selected: "+f.name);log("Type: "+(f.type||"unknown"),f.type==="video/mp4"?"ok":"warn");video.onloadedmetadata=()=>{mediaInfo()};video.oncanplay=()=>log("Local video canplay 🟢")};

$("createBtn").onclick=()=>{if(!$("videoInput").files[0])return alert("MP4/video file එකක් select කරන්න.");if(!initFirebase()||!capture())return;isHost=true;roomId=rid();$("roomLink").value=roomURL(roomId);$("copyBtn").disabled=false;$("role").textContent="HOST";peer=new Peer("wt-"+roomId,{debug:2});log("Host Peer created");peer.on("open",id=>{log("Host Peer OPEN: "+id);db.ref("rooms/"+roomId).set({hostPeer:id,playing:false,time:0,users:1});status("Room ready 🟢");$("videoHint").textContent="Waiting for Guest..."});peer.on("connection",c=>{conn=c;log("Guest data connection received");wire(c)});peer.on("call",c=>{log("Incoming one-way media call 🟢");mediaCall=c;if(!localStream)capture();c.answer(localStream);log("Host answered with local MediaStream 🟢");c.on("close",()=>log("Guest media call closed","warn"));c.on("error",e=>log("Host media error: "+e.message,"bad"))});peer.on("error",e=>{log("Peer error: "+e.type+" "+(e.message||""),"bad");status("Peer error")})};

$("joinBtn").onclick=async()=>{if(!initFirebase())return;let id=new URLSearchParams(location.search).get("room")||$("roomLink").value.split("room=")[1];if(!id)return alert("Host room link එක open කරන්න.");roomId=decodeURIComponent(id);isHost=false;$("role").textContent="GUEST";peer=new Peer({debug:2});log("Guest Peer created");peer.on("open",async myId=>{log("Guest Peer OPEN: "+myId);const s=await db.ref("rooms/"+roomId).get();if(!s.exists()){log("Room not found","bad");return}const host=s.val().hostPeer;log("Host Peer found: "+host);conn=peer.connect(host,{reliable:true});wire(conn);status("Requesting video...");mediaCall=peer.call(host);if(!mediaCall){log("peer.call returned NULL","bad");return}log("ONE-WAY media call created (no guest media) 🟢");mediaCall.on("stream",stream=>{log("REMOTE MEDIA STREAM RECEIVED 🟢");log("Remote video tracks: "+stream.getVideoTracks().length,stream.getVideoTracks().length?"ok":"bad");log("Remote audio tracks: "+stream.getAudioTracks().length,stream.getAudioTracks().length?"ok":"warn");video.srcObject=stream;video.removeAttribute("src");video.load();$("videoHint").textContent="Remote stream received 🟢";video.onloadedmetadata=()=>{mediaInfo();video.play().then(()=>{status("Live video 🟢");log("Remote video playing 🟢")}).catch(e=>{status("Click Play");log("Autoplay blocked: "+e.message,"warn")})};});mediaCall.on("close",()=>log("Media call closed","bad"));mediaCall.on("error",e=>log("Guest media error: "+e.message,"bad"))});peer.on("call",c=>{log("Unexpected incoming call","warn");c.close()});peer.on("error",e=>{log("Guest Peer error: "+e.type+" "+(e.message||""),"bad");status("Peer error")})};

function wire(c){c.on("open",()=>{log("DATA connection OPEN 🟢");status("Connected 🟢");send(isHost?{type:"state",playing:!video.paused,time:video.currentTime}:{type:"request-state"})});c.on("data",m=>{if(m.type==="state"&&!isHost){const t=Number(m.time)||0;if(Math.abs((video.currentTime||0)-t)>.4)video.currentTime=t;m.playing?video.play().catch(()=>{}):video.pause()}if(m.type==="request-state"&&isHost)send({type:"state",playing:!video.paused,time:video.currentTime});if(m.type==="chat")chat(m.name||"User",m.text||"")});c.on("close",()=>log("DATA connection closed","warn"));c.on("error",e=>log("DATA error: "+e.message,"bad"))}
function sync(){if(!isHost)return;const x={type:"state",playing:!video.paused,time:video.currentTime};send(x);if(db&&roomId)db.ref("rooms/"+roomId).update({playing:x.playing,time:x.time})}
video.addEventListener("play",sync);video.addEventListener("pause",sync);video.addEventListener("seeked",sync);
$("copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("roomLink").value);status("Copied ✓");log("Room link copied")}catch(e){log("Clipboard failed","bad")}};
$("sendBtn").onclick=()=>{const t=$("chatInput").value.trim();if(!t)return;chat("You",t);send({type:"chat",name:"User",text:t});$("chatInput").value=""};$("chatInput").onkeydown=e=>{if(e.key==="Enter")$("sendBtn").click()};
window.addEventListener("load",()=>{const id=new URLSearchParams(location.search).get("room");if(id)$("roomLink").value=roomURL(id);if(initFirebase())status("Ready 🟢")});
})();